name: Despliegue

on:
  push:
    branches:
      - main
jobs:
  despliegue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-node@v1 #this installs node and npm for us
      with:
        node-version: '16.x'
    - uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Instalando modulos de node
      run: |
        npm install
        npm run-script deploy
    - name: Instalando en gh-pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist/geoBog
    - name: Generando proyecto compilado
      run: |
        npm run-script deploy
    - name: Enviando el proyecto por ftp al servidor
      uses: airvzxf/ftp-deployment-action@latest
      with:
          server: ftp.themisapp.com.co
          user: jessi@geobog.themisapp.com.co
          password: dqh!fzy1ymh9ABK.vqd
          local_dir: "./dist/geoBog"
          delete: "true"
